org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/fitting/functions/IFunctionFactoryExtensionService.java

This renames existing and adds new interface methods which are needed to support function factory in python interpreter.

Renames register method and adds getPlugins method.

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/IPaletteListener.java

rescale setting (i.e. lock histogram).

Add in a rescaleHistogramChanged to notify listeners about changes to

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/AbstractClientProvider.java

Before showing the error check if this is GDA by lookaing at the
gda.mode
system property. If it is GDA dont show the error.

MXGDA-2305 Suppress SCISOFT_RMI_PORT error when starting GDA servers

---

org.eclipse.dawnsci.plotting.examples/src/org/eclipse/dawnsci/plotting/examples/SourceCodeView.java

This is just for fun, please feel free not to merge if you prefer.

Use monospaced font for source view of example plots

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/IPlottingSystem.java

Make javadoc render nicely in Eclipse

---

org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/AbstractStreamer.java

Prevent an exception killing off the MJPG streamer daemon thread

---

org.eclipse.dawnsci.hdf5/META-INF/MANIFEST.MF

Fix duplicate inclusion of OSGi xml file

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/tree/DataNode.java
org.eclipse.dawnsci.analysis.tree/src/org/eclipse/dawnsci/analysis/tree/impl/DataNodeImpl.java
org.eclipse.dawnsci.nexus/.pydevproject
org.eclipse.dawnsci.nexus/autogen/org/eclipse/dawnsci/nexus/NexusNodeFactory.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/AbstractNexusProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/AxisDevice.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/DelegateNexusProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/NexusDataBuilder.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/NexusObjectProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/impl/NXobjectImpl.java

[Nexus] reworked NexusDataBuilder and DefaultNexusDataBuilder. Added AxisDevice class to configure how a device should be added to an NXdata group.

[Nexus] reworked NexusDataBuilder and DefaultNexusDataBuilder.

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java

The size of fixed length strings is now accounted for when estimating
chunk sizes, preventing erroneously large chunk sizes.

Correct chunk estimation to account for fixed-length strings.

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusUtils.java

Merges the chunking changes into master.

Merge gda-8.master

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/file/NexusFileTest.java

External links to other HDF5 files can be specified using SymbolicNodes
with the correct URI parameter when creating a NexusFile using a
provided tree structure.

Allow external links to be specified with SymbolicNodes

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/builder/impl/DefaultNexusDataBuilderTest.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NXobject.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/AbstractNexusProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/DataDevice.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/NexusDataBuilder.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/NexusObjectProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/appdef/impl/TomoApplicationBuilder.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/impl/DefaultNexusDataBuilder.java

[Nexus] allow multiple NXdata groups for devices

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/IVolumeRenderTrace.java

The other pull request went a little bit pear shaped and got a bit too confusing to fix.
Learnt from my mistakes, made a new branch.
Signed-off-by: Joel Ogden <joel.ogden@diamond.ac.uk>

Simple volume render trace.

---

org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/INexusDevice.java

Signed-off-by: James Mudd <james.mudd@diamond.ac.uk>

Add JavaDoc to INexusDevice

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/remote/ThreadSafeTrace.java
org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/IVolumeRenderTrace.java

Signed-off-by: Joel Ogden <joel.ogden@diamond.ac.uk>

Added colour and opacity to the volume trace

---

org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/impl/BroadcastUtils.java
org.eclipse.dawnsci.analysis.examples/src/org/eclipse/dawnsci/analysis/examples/dataset/impl/BroadcastIteratorTest.java

Lengthen method name and update javadoc of parameter

Lengthen method name

---

org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/impl/AbstractDataset.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/impl/BroadcastUtils.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/impl/Dataset.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/impl/DatasetUtils.java
org.eclipse.dawnsci.analysis.examples/src/org/eclipse/dawnsci/analysis/examples/dataset/impl/BroadcastIteratorTest.java

This allows different shaped datasets to be combined in various operations

Implement new method to create a broadcast view of a dataset

---

org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusScanInfo.java

Signed-off-by: James Mudd <james.mudd@diamond.ac.uk>

Fix incorrect chunk estimations for anything other than 2D data

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java

Change NexusFileHDF5 to use the fill value provided by a lazy dataset

---

org.eclipse.dawnsci.analysis.api/META-INF/MANIFEST.MF
org.eclipse.dawnsci.analysis.dataset/META-INF/MANIFEST.MF
org.eclipse.dawnsci.hdf5.editor/META-INF/MANIFEST.MF
org.eclipse.dawnsci.hdf5/META-INF/MANIFEST.MF
org.eclipse.dawnsci.nexus/META-INF/MANIFEST.MF
org.eclipse.dawnsci.plotting.api/META-INF/MANIFEST.MF
org.eclipse.dawnsci.slicing.api/META-INF/MANIFEST.MF

Matching change already accepted on branch gda-8.master

DAQ-11 Fix dependency version ranges on slf4j and logging bundles

---

org.eclipse.dawnsci.hdf5/OSGI-INF/hierarchicalFileExecutionVisitor.xml

Update service definition to match new package name

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/remote/ThreadSafeTrace.java
org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/IVolumeRenderTrace.java

Signed-off-by: Joel Ogden <joel.ogden@diamond.ac.uk>

Improving the volume trace.

---

org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/dyn/DataConnection.java
org.eclipse.dawnsci.remotedataset.core/OSGI-INF/serviceHolder.xml
org.eclipse.dawnsci.remotedataset.core/src/org/eclipse/dawnsci/remotedataset/ServiceHolder.java
org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/slice/SliceRequest.java

http://jira.diamond.ac.uk/browse/DAQ-95

Make dependencies on IImageService and IPlotImageService optional

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/impl/NXobjectTest.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NXobject.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/impl/NXobjectImpl.java

[DAQ-81] added method to add fixed size lazy writable dataset

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/remote/ThreadSafeTrace.java
org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/ILine3DTrace.java
org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/IPlane3DTrace.java

Signed-off-by: Joel Ogden <joel.ogden@diamond.ac.uk>

Renamed plane trace, added line trace.

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/builder/impl/DefaultNexusEntryBuilderTest.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/AbstractNexusObjectProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/NexusObjectProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/impl/DefaultNexusEntryBuilder.java

[DAQ-146] support adding nexus object to a collection

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/builder/impl/DefaultNexusFileBuilderTest.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/impl/DefaultNexusFileBuilder.java

[DAQ-105] create parent dir for nexus file if it doesn't exist

---

org.eclipse.dawnsci.nexus.test/META-INF/MANIFEST.MF

http://jira.diamond.ac.uk/browse/DAQ-147

Fixed hamcrest version to match orbit (build fails if 1.1)

---

org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/AbstractNexusObjectProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/data/DataDeviceBuilder.java

fix NPE when nexus object provider primary data field not set

---

org.eclipse.dawnsci.analysis.api/.gitignore
org.eclipse.dawnsci.analysis.asserts/.gitignore
org.eclipse.dawnsci.analysis.dataset.test/.gitignore
org.eclipse.dawnsci.analysis.dataset/.gitignore
org.eclipse.dawnsci.analysis.examples/.gitignore
org.eclipse.dawnsci.analysis.tree/.gitignore
org.eclipse.dawnsci.doe/.gitignore
org.eclipse.dawnsci.hdf5.editor/.gitignore
org.eclipse.dawnsci.hdf5.model.test/.gitignore
org.eclipse.dawnsci.hdf5.model/.gitignore
org.eclipse.dawnsci.hdf5.test/.gitignore
org.eclipse.dawnsci.hdf5/.gitignore
org.eclipse.dawnsci.json.test/.gitignore
org.eclipse.dawnsci.json/.gitignore
org.eclipse.dawnsci.macro.api/.gitignore
org.eclipse.dawnsci.nexus.test/.gitignore
org.eclipse.dawnsci.nexus/.gitignore
org.eclipse.dawnsci.plotting.api/.gitignore
org.eclipse.dawnsci.plotting.examples/.gitignore
org.eclipse.dawnsci.remotedataset.client/.gitignore
org.eclipse.dawnsci.remotedataset.core/.gitignore
org.eclipse.dawnsci.remotedataset.server/.gitignore
org.eclipse.dawnsci.remotedataset.test/.gitignore
org.eclipse.dawnsci.slicing.api/.gitignore

DASCTEST-359 Fix .nfs pattern in standard .gitignore files

---

org.eclipse.dawnsci.analysis.dataset.test/releng.ant
org.eclipse.dawnsci.analysis.dataset/buckminster.cspex
org.eclipse.dawnsci.nexus.test/releng.ant
org.eclipse.dawnsci.nexus/buckminster.cspex

Add Buckminster dependency from plugins to their test fragment

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/persistence/IMarshaller.java

[DAQ-16] improve generics of IMarshaller so it's easier to implement

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/test/MultipleThreadNexusFileWriteTest.java

fix for MultipleThreadNexusFileWriteTest, increase timeout

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/IOperationBean.java

Change persistence to processing for clarity

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/IOperationBean.java

update to operation bean

---

org.eclipse.dawnsci.third.feature/feature.xml

org.eclipse.scanning.example.XXX.product(s) to run!

Added extra plugins to feature. Important, this is required for

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/histogram/ImageServiceBean.java

Switch to anti-clockwise order so we can use its ordinal value to calculate image rotation and add some methods

Improve image origin enumeration

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/AbstractOperationModel.java

Only display those fields that have not been marked as visible == false
in their OperationModelFieldAnnotation

AbstractOperationModel::isModelField: check for visible

---

org.eclipse.january.asserts/src/org/eclipse/january/asserts/TestUtils.java
org.eclipse.january.test/src/org/eclipse/january/dataset/SliceNDIteratorTest.java
org.eclipse.january/src/org/eclipse/january/dataset/SliceNDIterator.java

This helps iterate through slices of a scan and its data. Add unit test and another test print method

Add used slice output

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/IOperationBean.java

also update args of other methods to match method names

[DAQ-331] add setScanRank to IOperationBean

---

org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/operations/AbstractOperation.java

@jacobfilik Could you review this before it's merged in?
Thanks!

AbstractOperation: add support for rank ANY -> 1D

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/SimpleNexusFileTest.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/data/impl/DataFieldModel.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/data/impl/DefaultNexusDataBuilder.java

[DAQ-345] changes to allow scalar lazy datasets

---

org.eclipse.dawnsci.hdf5.test/releng.ant

Update testing classpath

---

org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/IMultipleNexusDevice.java

[DAQ-355] add interface for device that provide multiple nexus objects

---

org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/AbstractNonBlockingStreamer.java
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/MJPGStreamer.java
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/StreamerFactory.java
org.eclipse.dawnsci.remotedataset.test/src/org/eclipse/dawnsci/remotedataset/test/server/SliceClientTest.java

Made the MJpegStreamer use a non blocking implementation.
http://jira.diamond.ac.uk/browse/DAQ-298

Improve MJpeg performance

---

org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/AllSuite.java
org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/RectangularRoiTest.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/RectangularROI.java

http://jira.diamond.ac.uk/browse/DAQ-356

Fixed the RectangularROI bounds() method.

---

org.eclipse.dawnsci.slicing.api/src/org/eclipse/dawnsci/slicing/api/data/AbstractTransferableDataObject.java

Not sure if it will break anything else as the code is magical

Fix labelling of y axes in data browsing's data table

---

org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/AbstractNonBlockingStreamer.java

http://jira.diamond.ac.uk/browse/DAQ-298

Fix to MJpeg Streamer received images count

---

org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/AbstractNonBlockingStreamer.java
org.eclipse.dawnsci.remotedataset.test/src/org/eclipse/dawnsci/remotedataset/test/server/SliceClientTest.java

http://jira.diamond.ac.uk/browse/DAQ-298

Made MJpegStreamer blocking again but retained change to polling thread

---

org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/AbstractNonCachingStreamer.java
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/MJPGStreamer.java

http://jira.diamond.ac.uk/browse/DAQ-298

Make MJpeg streaming faster - only read last image in buffer

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/builder/data/impl/DefaultNexusDataBuilderTest.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusUtils.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/AbstractNexusObjectProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/NexusObjectProvider.java

[DAQ-355] can add multiple external files to nexus provider

---

org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/AbstractNexusObjectProvider.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/builder/NexusObjectProvider.java

[DAQ-355] ability to associate arbitrary properties with nexus object

---

org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/info/InfoServlet.java

http://jira.diamond.ac.uk/browse/DAQ-361

Swallowed another erroneous error.

---

org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/RectangularRoiTest.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/RectangularROI.java

http://jira.diamond.ac.uk/browse/DAQ-356

Trivial spelling mistake fix

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/file/NexusFileTest.java

Fix node listings over relative external links

---

org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/slicer/DynamicSliceViewIterator.java

add data size to constructor

---

org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/roi/AllSuite.java
org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/roi/ROISliceTest.java
org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/roi/ROITest.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/PolylineROI.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/RectangularROI.java

Change rectangular ROI's null constructor to have NaNs for its corner point, fix polyline, move ROI tests and add extra tests

Fix polyline get bounds when it has no points

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/MetadataPlotUtils.java

reset axes and clear traces, leave regions

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf/object/nexus/NexusUtils.java

better support for 2D axes

---

org.eclipse.dawnsci.nexus/META-INF/MANIFEST.MF

This bundle contributes INexusFileFactory which is widely referenced and
should require minimal dependencies.

Reduce dependencies.

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5File.java
org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5Utils.java

Also remove unused method, add explicit exception for unsupported reference object data and clean up code

Remove use of high level object API

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5Utils.java

It was put in place to speed up some cross-chunk cases but does not handle cases where part chunks need to be read too

Remove custom chunk handling to fix SCI-5784

---

org.eclipse.dawnsci.json.test/src/org/eclipse/dawnsci/json/test/JsonMarshallerInbuiltTypesTest.java
org.eclipse.dawnsci.json/src/org/eclipse/dawnsci/json/ArrayRegistry.java
org.eclipse.dawnsci.json/src/org/eclipse/dawnsci/json/MarshallerService.java

This allows String[] and ArrayList to serialize with different type id.

Added ArrayRegistry

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5FileFactory.java
org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java

Stops cached datasets being flushed and closed after they are closed

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusFile.java

Necessary for http://jira.diamond.ac.uk/browse/SCI-5390

Add getAttributeValue method

---

org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/RemoteDataset.java

Make loader in constructor instead of on connect

---

org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusScanInfo.java

[DAQ-474] add scan shape to NexusScanInfo

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java

Dropped the chunking message level down a notch.

Chunking message

---

org.eclipse.dawnsci.targetplatform/org.eclipse.dawnsci.targetplatform.target
org.eclipse.dawnsci.third.site/README.txt

Updated the Jython in the target to use versions because James made fixes to Jython

Made target platform correct again.

---

org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/slicer/DynamicSliceViewIterator.java

add timeout to log

---

org.eclipse.dawnsci.analysis.api/.pydevproject
org.eclipse.dawnsci.hdf5/.pydevproject

Signed-off-by: Matthew Gerring <matthew.gerring@gmail.com>

Removed pydev setting to remove pydev errors

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java

Signed-off-by: Matthew Gerring <matthew.gerring@gmail.com>

Reduced log level as existing message appears a lot and bothers people.

---

org.eclipse.dawnsci.json/src/org/eclipse/dawnsci/json/internal/ROIClassRegistry.java
org.eclipse.dawnsci.third.feature/feature.xml

Added dependency on spring and aop because Keith inadvertently put these in as dependencies of Jython. This should be put right ASAP but a workaround is needed for now.

Dawn third workaround

---

org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/test/util/NexusAssert.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusScanInfo.java

[DAQ-594] add NexusRole enum for per-point or per-scan nexus writing

---

org.eclipse.dawnsci.analysis.api/.pydevproject
org.eclipse.dawnsci.analysis.dataset/.pydevproject
org.eclipse.dawnsci.analysis.tree/.pydevproject
org.eclipse.dawnsci.hdf5/.pydevproject
org.eclipse.dawnsci.nexus/.pydevproject
org.eclipse.dawnsci.plotting.api/.pydevproject

Replace explicit project directory names and configure all plugins to the same interpreter

Update PyDev project settings

---

org.eclipse.dawnsci.json.test/src/org/eclipse/dawnsci/json/test/JsonMarshallerCustomClassesTest.java
org.eclipse.dawnsci.json.test/src/org/eclipse/dawnsci/json/test/JsonMarshallerInbuiltTypesTest.java
org.eclipse.dawnsci.json/src/org/eclipse/dawnsci/json/ArrayRegistry.java

[DAQ-609] add Object array to array class registry

---

org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/MaskCircularBufferTest.java
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/mask/MaskCircularBuffer.java

Add a class that acts as a circular buffer of masking steps

---

org.eclipse.dawnsci.plotting.api/.classpath
org.eclipse.dawnsci.plotting.api/.settings/org.eclipse.jdt.core.prefs
org.eclipse.dawnsci.plotting.api/META-INF/MANIFEST.MF
org.eclipse.dawnsci.plotting.api/build.properties
org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/remote/ThreadSafePlottingSystem.java
org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/trace/ITraceSystem.java
org.eclipse.dawnsci.remotedataset.client/META-INF/MANIFEST.MF
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/dyn/DynamicImage.java
pom.xml

With default implementation!
Enforces Java 1.8 requirement

SCI-5903: add new method getTracesByClass to ITraceSystem

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/conversion/IConversion.java
org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/conversion/IConversionContext.java
org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/conversion/IConversionScheme.java
org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/conversion/IConversionSchemeService.java
org.eclipse.dawnsci.plotting.examples/OSGI-INF/component.xml
org.eclipse.dawnsci.plotting.examples/src/org/eclipse/dawnsci/plotting/examples/Examples.java
org.eclipse.dawnsci.plotting.examples/src/org/eclipse/dawnsci/plotting/examples/exercises/Exercise3.java

* New interface IConversion
* New interface IConversionScheme, replacing enum IConversionContext.ConversionScheme
* New Interface IConversionSchemeService

SCI-5908: refactor and improve Conversion API

---

org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusScanInfo.java

[DAQ-805] add filePath to NexusScanInfo, rename monitor methods

---

org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/slicer/SliceInformation.java

Increase number of data dims when filling dimension

---

org.eclipse.dawnsci.hdf5.editor/src/org/eclipse/dawnsci/hdf5/editor/H5ValuePage.java

Broken by commit e2cf15fd945b7b80a5817a72cfc3d15d9be23e15

Fix H5ValuePage to show values

---

org.eclipse.dawnsci.targetplatform/org.eclipse.dawnsci.targetplatform.target

Update location of upstream p2 site

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/AbstractOperationModel.java
org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/ModelField.java

Cleanup in org.dawnsci.processing.ui.model

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5LazyLoader.java
org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5Utils.java

@tschoonj we need to provide the method for other users too

Add 5 second timeout and caching to local hostname resolution

---

org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/operations/AbstractOperationBase.java

Some type arguments are not classes but type variables

Fix class cast exceptions

---

org.eclipse.dawnsci.analysis.api/schema/operation.exsd
org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/operations/AbstractOperationBase.java

Make model attribute optional and correct class name

Clean up operations

---

org.eclipse.dawnsci.analysis.dataset.test/src/org/eclipse/dawnsci/analysis/dataset/MaskCircularBufferTest.java

It does returns a Number for non-compound, numeric datasets

Fix assumption that sum returns a Double

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java

Tracing errors is easier with non-generic exception messages.

Improve exception messages for NexusFileHDF5

---

org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/ActionType.java
org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/PlotType.java

SCI-6158: add enum constants for DataTables

---

org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5Utils.java
org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusUtils.java

This removes AxisEditingSupport's dependency on the old HDF Object API. It replaces
. https://github.com/eclipse/dawnsci/commit/e775ba0932d10affff81778bff8094f71780b1bc
. https://github.com/eclipse/dawnsci/commit/b5372443b07b61629cb1eae12ea1e1126e444ad2
. https://github.com/eclipse/dawnsci/commit/93d2e40e33c41efa2c7813b17743e090dd1035bc
. https://github.com/eclipse/dawnsci/commit/b20f1b08fb8bbcebbda902b595ef56138887f10c
in the [HDF_Object_removal](https://github.com/eclipse/dawnsci/tree/HDF_Object_removal) branch

Hdf object cleanup

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/io/IRemoteDatasetService.java
org.eclipse.dawnsci.remotedataset.client/META-INF/MANIFEST.MF
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/RemoteDataHolder.java
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/RemoteDatasetInfo.java
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/RemoteDatasetServiceImpl.java
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/RemoteLoader.java
org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/URLBuilder.java

To have a remote dataholder, which should simplify downstream code

Refactor remote dataset

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/ModelField.java
org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/OperationModelField.java

This will be used to display more verbose text in tooltips
Signed-off-by: Peter Chang <peter.chang@diamond.ac.uk>

Add a description parameter to model field annotation

---

org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/persistence/IJSonMarshaller.java
org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/persistence/IPersistenceService.java
org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/persistence/IPersistentFile.java

Make persistent file auto-closeable
