- org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/ModelUtils.java
- org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/OperationModelField.java
useful when overriding the default alphabetic sorting of the field is required
> OperationModelField: added fieldPosition

- org.eclipse.dawnsci.hdf5.test/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5Test.java
- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5FileFactory.java
- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5FileResource.java
- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5GroupResource.java
- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5Utils.java
- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
- org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/NexusFileTest.java
The HDF5 library does not support use of SWMR with datasets of variable length types.
If we are creating a file for use with SWMR writing, any string datasets should be fixed-length.
> Fixes for SWMR

- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5FileFactory.java
- org.eclipse.dawnsci.nexus.test/JUnit-org.eclipse.dawnsci.nexus.test.launch
Change to allow HDF5FileFactory to overwrite files when the existing file id in the cache is not being used and is awaiting cleanup.
> Allow creation of HDF5 files when existing file ids are unusued.

- org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusUtils.java
Allows providing partial dimensions for chunking when getting an estimate. The provided dimensions will be fixed and the other dimensions will be scaled.
Useful, for example, when we would like to prevent a detector image from being haphazardly split across several chunks.
> Chunk estimating improvements

- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusUtils.java
Axes that specify a primary are always weighted above ones that don't.
> Fix getAxes to always order axis datasets over non-axis datasets

- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
We use the topology of the graph structure of the passed nodes to work
out where to create hard links. This change allows this to continue to
work when nodes have the equals method overridden.
> Use IdentityHashMap when handling nodes passed to NexusFileHDF5

- org.eclipse.dawnsci.nexus/src/org/eclipse/dawnsci/nexus/NexusUtils.java
The original strategy produced a chunk that was balanced according to
the expected data dimensions - this is reasonable if processors are
likely to slice over different dimensions but it is not so good for
writing or processing single detector images at a time.
The new strategy ("skew") weights the chunk dimensions toward the last
dimensions, reducing earlier dimensions to one before moving to the next
(or until the chunk is under the target size - usually 1MB).
This is made the default as it is more likely to cater for the common
case when people forget to specify chunking.
> Add new skew strategy for estimating chunking and make default

- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/PolylineROI.java
This fixes a bug seen in the GDA client where the ROI given by a
ROIChanged event had an incorrect first point.
> Ensure first point of PolylineROI's point list stays in sync with spt

- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5Utils.java
- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
h5py has various issues with unicode strings.
Also changes H5Utils to match the character set when writing a dataset
slice.
> Prefer ASCII strings in NexusFileHDF5.

- org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/DataServer.java
This does NOT solve the issue of Spring finding the class to actually
instantiate a data server, only the thread blocking issue.
http://jira.diamond.ac.uk/browse/DAQ-82
> Allow DataServer to start up as an application or a Spring bean

- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
- org.eclipse.dawnsci.nexus.test/src/org/eclipse/dawnsci/nexus/file/NexusFileTest.java
Creating a hard link will automatically create an attribute called "target" that records the original location (for compatibility with NAPI). This would overwrite an existing "target", which may be specified ahead of time, particularly if you're passing a node tree to save to disk and want a specific location to count as the "original" (the order of creation is unspecified when passing a tree).
> Do not overwrite target attribute on hard links

- org.eclipse.dawnsci.remotedataset.client/src/org/eclipse/dawnsci/remotedataset/client/streamer/AbstractStreamer.java
Signed-off-by: James Mudd <james.mudd@gmail.com>
> Fix mjpeg stream when "boundary=" tag is not prefixed with \\;

- org.eclipse.dawnsci.analysis.examples/META-INF/MANIFEST.MF
- org.eclipse.dawnsci.hdf5.model.test/META-INF/MANIFEST.MF
- org.eclipse.dawnsci.hdf5.test/META-INF/MANIFEST.MF
- org.eclipse.dawnsci.json.test/META-INF/MANIFEST.MF
- org.eclipse.dawnsci.nexus.test/META-INF/MANIFEST.MF
- org.eclipse.dawnsci.remotedataset.test/META-INF/MANIFEST.MF
> Matthew Webber said that junit should be 4.12 minimum because 4.10

- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/LinearROI.java
The endpt is a transient variable and shouldn't have been added in the auto generated equals method
> Remove compare on endpt in equals method

- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/nexus/NexusFileHDF5.java
H5Lexists "fails" if any part of the path to test does not exist (except
the last name). Whilst we can catch the resulting exception and just
return false, this can result in a noisy message being printed to stderr
by the library, which we would like to avoid.
We follow the recommendation in the HDF5 reference to test the path
incrementally.
> Incrementally test link path in NexusFileHDF5 when validating.

- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/operations/AbstractOperationBase.java
Also created a version of copyMetadata with a flag for AxesMetadata
> AbstractOperationBase: copyMetadata made static

- org.eclipse.january/src/org/eclipse/january/metadata/internal/AxesMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/DimensionMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/ErrorMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/MaskMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/OriginMetadataImpl.java
- org.eclipse.january/src/org/eclipse/january/metadata/internal/PeemMetadataImpl.java
This reverts commit 9cbe91e8722e1a83aacf9b49080897081de769c4.
> Revert "Remove public access to metadata constructors"

- org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/region/ColorConstants.java
> Made ColorConstants public because can use it then without a draw2d

- org.eclipse.january.test/src/org/eclipse/january/dataset/AbstractDatasetTest.java
- org.eclipse.january.test/src/org/eclipse/january/dataset/StrideIteratorTest.java
- org.eclipse.january/src/org/eclipse/january/dataset/StrideIterator.java
This causes premature termination of any iteration by simplifying end condition checking. Add more coverage of stride uses
> Fix case where negative strides bug

- org.eclipse.january/src/org/eclipse/january/dataset/DataListenerDelegate.java
Previously deadlock was possible if a listener was running in the same
thread as a call attempting to add or remove listeners. As might be
commonly the case for the UI thread.
Also replaced the listeners List with a Set to prevent duplicate
listeners being added. Using a set backed by a ConcurrentHashMap should
allow all operation to complete safely without requiring external
synchronized, this allows the methods in the class to be simplified.
Signed-off-by: James Mudd <james.mudd@diamond.ac.uk>
> Improve thread safety around adding and removing IDataListener's

- org.eclipse.dawnsci.analysis.dataset.test/releng.ant
- org.eclipse.dawnsci.hdf5.model.test/releng.ant
- org.eclipse.dawnsci.hdf5.test/releng.ant
- org.eclipse.dawnsci.json.test/releng.ant
- org.eclipse.dawnsci.nexus.test/releng.ant
Normally, org.eclipse.january* is jars in the target platform,
however it is also possible to check it out as source projects.
This change supports testing in the latter case.
> TESTING: update testing classpath when January source checkout used

- org.eclipse.dawnsci.json.test/src/org/eclipse/dawnsci/json/test/JsonMarshallerClassRegistryTest.java
- org.eclipse.dawnsci.json/src/org/eclipse/dawnsci/json/internal/MarshallerServiceClassRegistry.java
This is for the MarshallerService. This is due to DAWN having different
bundle dependencies, and thus requiring a separate class registry.
Signed-off-by: Martin Gaughran <martin.gaughran@diamond.ac.uk>
> Class id clash will only raise error if new class is different.

- org.eclipse.dawnsci.third.feature/README.txt
- org.eclipse.dawnsci.third.feature/feature.xml
This change removes many bundles which were erroneously in the third feature. These bundles are not needed by dawnsci and have been moved to org.eclipse.scanning.third.feature
> Target platform fix

- org.eclipse.dawnsci.analysis.api/.pydevproject
- org.eclipse.dawnsci.hdf5/.pydevproject
This reverts commit 04a15cae68826135449c37e8e09d2e154c5f4ced.
This setting is correct for running Jython scripts in PyDev.
> Revert "Removed pydev setting to remove pydev errors"

- org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/DataServer.java
- org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/info/InfoServlet.java
- org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/info/TreeServlet.java
- org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/slice/SliceRequest.java
- org.eclipse.dawnsci.remotedataset.server/src/org/eclipse/dawnsci/remotedataset/server/utils/DataServerUtils.java
Only clear dataholder cache on reading tree, might be a bit
controversial for tif images, but prevents entire tree read on every
slice of SWMR data
@gerring would you review and merge?
> Increase logging, change dataholder caching behavior

- org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/IOperationContext.java
- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/slicer/Slicer.java
Added a get/set-NumberOfCores routine to the IOperationContext as well as consumerate logic in the Slicer class to deal with changes to nProcessors
> Modifications for defining number of threads/cores to run

- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/handler/RectangularROIHandler.java
For SCI-5885, can now re-orient relative to opposite mid-point
> Add support for re-orientation of a rectangular ROI by mid-point of an edge

- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/operations/AbstractOperationBase.java
Until now getModelClass() assumed that the super class was parameterized. However, this is no longer true due to several new operations in scisoft-core that extend non-parameterized super classes. This commit fixes this behavior by going up through the inheritance hierarchy until a parameterized superclass is found.
> SCI-5975: getModelClass fix

- org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/ModelUtils.java
When such variables are encountered, they should not be considered when making a list of model fields provided by an operation model.
> SCI-6108: operation model fields cannot be static and/or final

- org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/AbstractOperationModel.java
- org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/model/ModelUtils.java
This commit fixes a bug that caused fields in parent model classes not to be detected if the parent was at least two levels removed from the examined model class.
> SCI-5975: ensure all fields in operation models are found

- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/PolylineROI.java
- org.eclipse.dawnsci.analysis.dataset/src/org/eclipse/dawnsci/analysis/dataset/roi/RectangularROI.java
We have some GUI code that uses reflections to instantiates ROIs but does not allow editing of fields with NaN values(!)
This is an alternative to commits 62635ae and d7a2ad0 for fixing DAQ-381
> Switch null constructor to something sensible

- org.eclipse.dawnsci.analysis.tree/src/org/eclipse/dawnsci/analysis/tree/impl/GroupNodeImpl.java
findNodeLink will return the node-link for such paths if it is a group or symbolic node that points to a group
> Allow pathname to end in Tree.SEPARATOR

- org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/histogram/ImageServiceBean.java
When a dataset is logged then the offset used for the minimum log value should scale with its values. The existing code works for integer datasets but fails for float datasets. The constant used (1e-6) should suffice to give decent contrast.
> Modify the offset used in log-scaled images

- org.eclipse.dawnsci.plotting.api/src/org/eclipse/dawnsci/plotting/api/histogram/ImageServiceBean.java
When a dataset is logged then the offset used for the minimum log value should scale with its values. The existing code works for integer datasets but fails for float datasets. The constant used (1e-6) should suffice to give decent contrast.
Use same contrast for integers except when less than one (#667)
> Modify the offset used in log-scaled images (#665)

- org.eclipse.dawnsci.hdf5/src/org/eclipse/dawnsci/hdf5/HDF5Utils.java
Datatype references are not handled at all so TODO add support for them
> Prevent NPE when HDF5 object reference types are encountered

- org.eclipse.dawnsci.analysis.api/src/org/eclipse/dawnsci/analysis/api/processing/IOperation.java
With an empty default implementation.
Should contain code to be executed when the IOperation is removed from the list of operations in the processing perspective for cleanup. This will be used to kill the background python interpreters generated by the Larch operations.
> SCI-7211: add destroy() method to IOperation
